### ISSUE TITLE
Uncatchable exception in pcb-stackup / gerber-plotter

### ISSUE THREAD

**Issue by vladiks** [tracespace/tracespace#355]
Hello,

I think, there is uncatchable error somewhere inside pcb-stackup tool. I can succesfully render svg using pcb-stackup with some gerber files. But when I include also this file [trg_paste_TOP.txt](https://github.com/tracespace/tracespace/files/5715712/trg_paste_TOP.txt) I get this error, which I am unable to catch at all (it originates from some async code?): 

```MYPATH\server\node_modules\gerber-plotter\lib\_operate.js:385
  if (tool.trace.length !== 1 && !region) {
           ^

TypeError: Cannot read property 'trace' of null
    at interpolate (MYPATH\server\node_modules\gerber-plotter\lib\_operate.js:385:12)
    at operate (MYPATH\server\node_modules\gerber-plotter\lib\_operate.js:436:13)
    at Plotter._transform (MYPATH\server\node_modules\gerber-plotter\lib\plotter.js:180:18)
    at Plotter.Transform._read (MYPATH\server\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at Plotter.Transform._write (MYPATH\server\node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite (MYPATH\server\node_modules\readable-stream\lib\_stream_writable.js:409:139)
    at writeOrBuffer (MYPATH\server\node_modules\readable-stream\lib\_stream_writable.js:398:5)
    at Plotter.Writable.write (MYPATH\server\node_modules\readable-stream\lib\_stream_writable.js:307:11)
    at Parser.ondata (MYPATH\server\node_modules\readable-stream\lib\_stream_readable.js:681:20)
    at Parser.emit (events.js:209:13)
```

My function for rendering looks like this:

```(fileNames) => {
	return new Promise((resolve, reject) => {
		try{
			const layers = fileNames.map(filename => ({
				filename,
				gerber: fs.createReadStream(filename),
				options : {
					backupUnits : "mm"
				}
			}))

			pcbStackup(layers, {backupUnits : "mm"}).then(stackup => {		
				fs.writeFileSync("top.svg", stackup.top.svg);
				fs.writeFileSync("bottom.svg", stackup.bottom.svg);
	
				resolve({
					top : stackup.top.svg,
					bottom : stackup.bottom.svg,
				})
			}).catch((err) => {
				reject(err)
			})
		}catch(err){
			reject(err)
		}
	})
```

None of resolve error blocks is hit and the script crashes.

**Comment by mcous** [comment]
Thanks for the report! Fix released as v4.2.5
